### PR TITLE
Added optionality of options and fixed options interface

### PR DESCRIPTION
**Pull request by fearistoff**

### CODE REVIEW

**Comment by fearistoff** [comment]
TypeScript can't check some properties of options object:

- `touchHoldTolerance`
- `dragFrequency`
- `rollOverFrequency`

And also doesn't allow not passing options object.

**Comment by robinrodricks** [comment]
Thanks for this fix!

**Comment by robinrodricks** [comment]
Published pls check:

vue3-touch-events@4.1.5

**Comment by fearistoff** [comment]
@robinrodricks everything works great! Thanks!

**Comment by robinrodricks** [comment]
Most welcome.

**Pull request merged**
